<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 17,
                'name' => '123',
                'email' => '123@gmail.com',
                'phone_number' => '12345678',
                'address' => NULL,
                'user_id' => '1',
                'product_name' => 'Iphone 15PM',
                'quantity' => '2',
                'price' => '40.000.000',
                'image' => '1717267099.jpg',
                'product_id' => '1',
                'payment_status' => 'paid',
                'delivery_status' => 'delivered',
                'created_at' => '2024-06-15 19:54:54',
                'updated_at' => '2024-06-22 09:46:27',
            ),
            1 => 
            array (
                'id' => 21,
                'name' => 'admin',
                'email' => 'admin@gmail.com',
                'phone_number' => '1234567',
                'address' => NULL,
                'user_id' => '5',
                'product_name' => 'casing magsafe',
                'quantity' => '1',
                'price' => '50.000',
                'image' => '1717439924.jpg',
                'product_id' => '12',
                'payment_status' => 'paid',
                'delivery_status' => 'delivered',
                'created_at' => '2024-06-22 16:24:47',
                'updated_at' => '2024-06-22 16:25:57',
            ),
            2 => 
            array (
                'id' => 19,
                'name' => 'admin',
                'email' => 'admin@gmail.com',
                'phone_number' => '1234567',
                'address' => NULL,
                'user_id' => '5',
                'product_name' => 'casing magsafe',
                'quantity' => '1',
                'price' => '200.000',
                'image' => '1717439941.jpg',
                'product_id' => '13',
                'payment_status' => 'paid',
                'delivery_status' => 'delivered',
                'created_at' => '2024-06-22 15:21:48',
                'updated_at' => '2024-06-22 18:13:23',
            ),
            3 => 
            array (
                'id' => 22,
                'name' => 'admin',
                'email' => 'admin@gmail.com',
                'phone_number' => '1234567',
                'address' => NULL,
                'user_id' => '5',
                'product_name' => 'Samsung S22 Ultra',
                'quantity' => '1',
                'price' => '15.000.000',
                'image' => '1717352880.jpg',
                'product_id' => '10',
                'payment_status' => 'COD/Transfer',
                'delivery_status' => 'processing',
                'created_at' => '2024-06-22 18:14:36',
                'updated_at' => '2024-06-22 18:14:36',
            ),
            4 => 
            array (
                'id' => 23,
                'name' => 'admin',
                'email' => 'admin@gmail.com',
                'phone_number' => '1234567',
                'address' => NULL,
                'user_id' => '5',
                'product_name' => 'Iphone 12PM',
                'quantity' => '1',
                'price' => '11.000.000',
                'image' => '1717352672.jpg',
                'product_id' => '7',
                'payment_status' => 'COD/Transfer',
                'delivery_status' => 'processing',
                'created_at' => '2024-06-22 18:14:36',
                'updated_at' => '2024-06-22 18:14:36',
            ),
            5 => 
            array (
                'id' => 20,
                'name' => 'admin',
                'email' => 'admin@gmail.com',
                'phone_number' => '1234567',
                'address' => NULL,
                'user_id' => '5',
                'product_name' => 'casing magsafe',
                'quantity' => '1',
                'price' => '500.000',
                'image' => '1717439617.jpg',
                'product_id' => '11',
                'payment_status' => 'paid',
                'delivery_status' => 'delivered',
                'created_at' => '2024-06-22 16:24:47',
                'updated_at' => '2024-06-22 18:14:54',
            ),
            6 => 
            array (
                'id' => 25,
                'name' => '321',
                'email' => '321@gmail.com',
                'phone_number' => '0987654321',
                'address' => NULL,
                'user_id' => '7',
                'product_name' => 'Iphone 14PM',
                'quantity' => '1',
                'price' => '18.000.000',
                'image' => '1717347928.jpg',
                'product_id' => '2',
                'payment_status' => 'cash on delivery',
                'delivery_status' => 'you canceled the order',
                'created_at' => '2024-06-23 18:13:17',
                'updated_at' => '2024-06-23 18:19:11',
            ),
            7 => 
            array (
                'id' => 28,
                'name' => '321',
                'email' => '321@gmail.com',
                'phone_number' => '0987654321',
                'address' => NULL,
                'user_id' => '7',
                'product_name' => 'Iphone 14PM',
                'quantity' => '1',
                'price' => '18.000.000',
                'image' => '1717347928.jpg',
                'product_id' => '2',
                'payment_status' => 'cash on delivery',
                'delivery_status' => 'processing',
                'created_at' => '2024-06-23 19:34:56',
                'updated_at' => '2024-06-23 19:34:56',
            ),
            8 => 
            array (
                'id' => 15,
                'name' => '123',
                'email' => '123@gmail.com',
                'phone_number' => '12345678',
                'address' => NULL,
                'user_id' => '1',
                'product_name' => 'Samsung S24 Ultra',
                'quantity' => '1',
                'price' => '19.000.000',
                'image' => '1717352731.jpg',
                'product_id' => '8',
                'payment_status' => 'paid',
                'delivery_status' => 'delivered',
                'created_at' => '2024-06-15 19:54:54',
                'updated_at' => '2024-06-22 06:03:39',
            ),
            9 => 
            array (
                'id' => 29,
                'name' => '321',
                'email' => '321@gmail.com',
                'phone_number' => '0987654321',
                'address' => NULL,
                'user_id' => '7',
                'product_name' => 'Samsung S22 Ultra',
                'quantity' => '1',
                'price' => '15.000.000',
                'image' => '1717352880.jpg',
                'product_id' => '10',
                'payment_status' => 'cash on delivery',
                'delivery_status' => 'processing',
                'created_at' => '2024-06-23 19:34:56',
                'updated_at' => '2024-06-23 19:34:56',
            ),
            10 => 
            array (
                'id' => 27,
                'name' => '321',
                'email' => '321@gmail.com',
                'phone_number' => '0987654321',
                'address' => NULL,
                'user_id' => '7',
                'product_name' => 'Iphone 14PM',
                'quantity' => '1',
                'price' => '18.000.000',
                'image' => '1717347928.jpg',
                'product_id' => '2',
                'payment_status' => 'cash on delivery',
                'delivery_status' => 'you canceled the order',
                'created_at' => '2024-06-23 18:29:42',
                'updated_at' => '2024-06-23 19:35:06',
            ),
            11 => 
            array (
                'id' => 30,
                'name' => '321',
                'email' => '321@gmail.com',
                'phone_number' => '0987654321',
                'address' => NULL,
                'user_id' => '7',
                'product_name' => 'casing magsafe',
                'quantity' => '1',
                'price' => '500.000',
                'image' => '1717439617.jpg',
                'product_id' => '11',
                'payment_status' => 'cash on delivery',
                'delivery_status' => 'processing',
                'created_at' => '2024-06-23 19:42:47',
                'updated_at' => '2024-06-23 19:42:47',
            ),
            12 => 
            array (
                'id' => 18,
                'name' => '123',
                'email' => '123@gmail.com',
                'phone_number' => '12345678',
                'address' => NULL,
                'user_id' => '1',
                'product_name' => 'Iphone 13PM',
                'quantity' => '1',
                'price' => '15.000.000',
                'image' => '1717352640.jpg',
                'product_id' => '6',
                'payment_status' => 'paid',
                'delivery_status' => 'delivered',
                'created_at' => '2024-06-15 19:55:13',
                'updated_at' => '2024-06-24 04:10:58',
            ),
            13 => 
            array (
                'id' => 31,
                'name' => '321',
                'email' => '321@gmail.com',
                'phone_number' => '0987654321',
                'address' => NULL,
                'user_id' => '7',
                'product_name' => 'casing magsafe',
                'quantity' => '1',
                'price' => '500.000',
                'image' => '1717439617.jpg',
                'product_id' => '11',
                'payment_status' => 'cash on delivery',
                'delivery_status' => 'processing',
                'created_at' => '2024-06-24 04:24:27',
                'updated_at' => '2024-06-24 04:24:27',
            ),
            14 => 
            array (
                'id' => 32,
                'name' => '321',
                'email' => '321@gmail.com',
                'phone_number' => '0987654321',
                'address' => NULL,
                'user_id' => '7',
                'product_name' => 'Iphone 15PM',
                'quantity' => '1',
                'price' => '32.323.232',
                'image' => '1719202827.png',
                'product_id' => '15',
                'payment_status' => 'cash on delivery',
                'delivery_status' => 'processing',
                'created_at' => '2024-06-24 04:24:27',
                'updated_at' => '2024-06-24 04:24:27',
            ),
        ));
        
        
    }
}